__author__ = "Bernd Husemann"
__credit__ = ['Bernd Husemann']
__copyright__ = "Copyright 2020, Bernd Husemann"
__license__ = "MIT"
__url__ = 'https://github.com/brandherd/QDeblend3D'
__maintainer__ = "Bernd Husemann"
__email__ = "berndhusemann@gmx.de"
__status__ = "Beta"
__version__ = "1.4.0b"
