# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './dlgMonteCarlo.ui'
#
# Created: Sun Feb  6 13:35:37 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_dlgMonteCarlo(object):
    def setupUi(self, dlgMonteCarlo):
        dlgMonteCarlo.setObjectName("dlgMonteCarlo")
        dlgMonteCarlo.resize(574, 382)
        self.verticalLayout_3 = QtGui.QVBoxLayout(dlgMonteCarlo)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(dlgMonteCarlo)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineVariance = QtGui.QLineEdit(dlgMonteCarlo)
        self.lineVariance.setReadOnly(True)
        self.lineVariance.setObjectName("lineVariance")
        self.horizontalLayout_3.addWidget(self.lineVariance)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(348, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.bVarSelect = QtGui.QPushButton(dlgMonteCarlo)
        self.bVarSelect.setObjectName("bVarSelect")
        self.horizontalLayout_4.addWidget(self.bVarSelect)
        spacerItem1 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(dlgMonteCarlo)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineDir = QtGui.QLineEdit(dlgMonteCarlo)
        self.lineDir.setEnabled(True)
        self.lineDir.setDragEnabled(False)
        self.lineDir.setReadOnly(True)
        self.lineDir.setObjectName("lineDir")
        self.horizontalLayout_2.addWidget(self.lineDir)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtGui.QSpacerItem(348, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.bDirSelect = QtGui.QPushButton(dlgMonteCarlo)
        self.bDirSelect.setObjectName("bDirSelect")
        self.horizontalLayout_5.addWidget(self.bDirSelect)
        spacerItem3 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem4 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(dlgMonteCarlo)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.linePrefix = QtGui.QLineEdit(dlgMonteCarlo)
        self.linePrefix.setObjectName("linePrefix")
        self.horizontalLayout.addWidget(self.linePrefix)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem5 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtGui.QLabel(dlgMonteCarlo)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.dBoxSimul = QtGui.QSpinBox(dlgMonteCarlo)
        self.dBoxSimul.setMinimum(1)
        self.dBoxSimul.setMaximum(10000)
        self.dBoxSimul.setProperty("value", 10)
        self.dBoxSimul.setObjectName("dBoxSimul")
        self.gridLayout_2.addWidget(self.dBoxSimul, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(dlgMonteCarlo)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.dBoxRandom = QtGui.QDoubleSpinBox(dlgMonteCarlo)
        self.dBoxRandom.setSpecialValueText("")
        self.dBoxRandom.setSuffix("")
        self.dBoxRandom.setDecimals(1)
        self.dBoxRandom.setObjectName("dBoxRandom")
        self.gridLayout_2.addWidget(self.dBoxRandom, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(dlgMonteCarlo)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.groupBox = QtGui.QGroupBox(dlgMonteCarlo)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.dStart = QtGui.QDoubleSpinBox(self.groupBox)
        self.dStart.setMaximum(99998.0)
        self.dStart.setSingleStep(0.1)
        self.dStart.setObjectName("dStart")
        self.gridLayout.addWidget(self.dStart, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.dEnd = QtGui.QDoubleSpinBox(self.groupBox)
        self.dEnd.setMaximum(100000.0)
        self.dEnd.setSingleStep(0.1)
        self.dEnd.setObjectName("dEnd")
        self.gridLayout.addWidget(self.dEnd, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout)
        self.horizontalLayout_8.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem7 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem8 = QtGui.QSpacerItem(288, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.buttonBox = QtGui.QDialogButtonBox(dlgMonteCarlo)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_6.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(dlgMonteCarlo)
        QtCore.QMetaObject.connectSlotsByName(dlgMonteCarlo)

    def retranslateUi(self, dlgMonteCarlo):
        dlgMonteCarlo.setWindowTitle(QtGui.QApplication.translate("dlgMonteCarlo", "Monte Carlo Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("dlgMonteCarlo", "Variance Cube:", None, QtGui.QApplication.UnicodeUTF8))
        self.bVarSelect.setText(QtGui.QApplication.translate("dlgMonteCarlo", "Open Variance...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("dlgMonteCarlo", "Directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.bDirSelect.setText(QtGui.QApplication.translate("dlgMonteCarlo", "Choose Dir...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("dlgMonteCarlo", "Prefix Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("dlgMonteCarlo", "Cube Realisations:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("dlgMonteCarlo", "Region border width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("dlgMonteCarlo", "Angstrom", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("dlgMonteCarlo", "Select Wavelength (Optional)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("dlgMonteCarlo", "End wavelength:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("dlgMonteCarlo", "Start wavelength:", None, QtGui.QApplication.UnicodeUTF8))

