# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './dlgColorProperties.ui'
#
# Created: Fri Jan  7 18:33:17 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_dlgColorProperties(object):
    def setupUi(self, dlgColorProperties):
        dlgColorProperties.setObjectName("dlgColorProperties")
        dlgColorProperties.setWindowModality(QtCore.Qt.WindowModal)
        dlgColorProperties.resize(777, 330)
        self.buttonBox = QtGui.QDialogButtonBox(dlgColorProperties)
        self.buttonBox.setGeometry(QtCore.QRect(160, 280, 611, 32))
        self.buttonBox.setAcceptDrops(False)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Open|QtGui.QDialogButtonBox.RestoreDefaults|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtGui.QTabWidget(dlgColorProperties)
        self.tabWidget.setGeometry(QtCore.QRect(30, 20, 701, 251))
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName("tab1")
        self.layoutWidget = QtGui.QWidget(self.tab1)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 20, 593, 184))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 5, 1, 2)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 7, 1, 2)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBoxCSpec1 = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxCSpec1.setObjectName("comboBoxCSpec1")
        self.comboBoxCSpec1.addItem("")
        self.comboBoxCSpec1.addItem("")
        self.comboBoxCSpec1.addItem("")
        self.comboBoxCSpec1.addItem("")
        self.comboBoxCSpec1.addItem("")
        self.comboBoxCSpec1.addItem("")
        self.gridLayout.addWidget(self.comboBoxCSpec1, 1, 1, 1, 1)
        self.comboBoxCSpec2 = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxCSpec2.setObjectName("comboBoxCSpec2")
        self.comboBoxCSpec2.addItem("")
        self.comboBoxCSpec2.addItem("")
        self.comboBoxCSpec2.addItem("")
        self.comboBoxCSpec2.addItem("")
        self.comboBoxCSpec2.addItem("")
        self.comboBoxCSpec2.addItem("")
        self.gridLayout.addWidget(self.comboBoxCSpec2, 1, 2, 1, 1)
        self.comboBoxCSlicer = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxCSlicer.setObjectName("comboBoxCSlicer")
        self.comboBoxCSlicer.addItem("")
        self.comboBoxCSlicer.addItem("")
        self.comboBoxCSlicer.addItem("")
        self.comboBoxCSlicer.addItem("")
        self.comboBoxCSlicer.addItem("")
        self.comboBoxCSlicer.addItem("")
        self.gridLayout.addWidget(self.comboBoxCSlicer, 1, 3, 1, 1)
        self.comboBoxCZoom = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxCZoom.setObjectName("comboBoxCZoom")
        self.comboBoxCZoom.addItem("")
        self.comboBoxCZoom.addItem("")
        self.comboBoxCZoom.addItem("")
        self.comboBoxCZoom.addItem("")
        self.comboBoxCZoom.addItem("")
        self.comboBoxCZoom.addItem("")
        self.gridLayout.addWidget(self.comboBoxCZoom, 1, 4, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 6, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.comboBoxSSpec1 = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxSSpec1.setObjectName("comboBoxSSpec1")
        self.comboBoxSSpec1.addItem("")
        self.comboBoxSSpec1.addItem("")
        self.comboBoxSSpec1.addItem("")
        self.comboBoxSSpec1.addItem("")
        self.gridLayout.addWidget(self.comboBoxSSpec1, 2, 1, 1, 1)
        self.comboBoxSSpec2 = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxSSpec2.setObjectName("comboBoxSSpec2")
        self.comboBoxSSpec2.addItem("")
        self.comboBoxSSpec2.addItem("")
        self.comboBoxSSpec2.addItem("")
        self.comboBoxSSpec2.addItem("")
        self.gridLayout.addWidget(self.comboBoxSSpec2, 2, 2, 1, 1)
        self.comboBoxSSlicer = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxSSlicer.setObjectName("comboBoxSSlicer")
        self.comboBoxSSlicer.addItem("")
        self.comboBoxSSlicer.addItem("")
        self.comboBoxSSlicer.addItem("")
        self.comboBoxSSlicer.addItem("")
        self.gridLayout.addWidget(self.comboBoxSSlicer, 2, 3, 1, 1)
        self.comboBoxSZoom = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxSZoom.setObjectName("comboBoxSZoom")
        self.comboBoxSZoom.addItem("")
        self.comboBoxSZoom.addItem("")
        self.comboBoxSZoom.addItem("")
        self.comboBoxSZoom.addItem("")
        self.gridLayout.addWidget(self.comboBoxSZoom, 2, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 6, 1, 2)
        self.comboBoxSSelect = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxSSelect.setObjectName("comboBoxSSelect")
        self.comboBoxSSelect.addItem("")
        self.comboBoxSSelect.addItem("")
        self.comboBoxSSelect.addItem("")
        self.comboBoxSSelect.addItem("")
        self.gridLayout.addWidget(self.comboBoxSSelect, 2, 8, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.spinBoxWSpec1 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.spinBoxWSpec1.setDecimals(1)
        self.spinBoxWSpec1.setMaximum(20.0)
        self.spinBoxWSpec1.setSingleStep(0.1)
        self.spinBoxWSpec1.setProperty("value", 1.0)
        self.spinBoxWSpec1.setObjectName("spinBoxWSpec1")
        self.gridLayout.addWidget(self.spinBoxWSpec1, 3, 1, 1, 1)
        self.spinBoxWSpec2 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.spinBoxWSpec2.setDecimals(1)
        self.spinBoxWSpec2.setMaximum(20.0)
        self.spinBoxWSpec2.setSingleStep(0.1)
        self.spinBoxWSpec2.setProperty("value", 1.0)
        self.spinBoxWSpec2.setObjectName("spinBoxWSpec2")
        self.gridLayout.addWidget(self.spinBoxWSpec2, 3, 2, 1, 1)
        self.spinBoxWSlicer = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.spinBoxWSlicer.setDecimals(1)
        self.spinBoxWSlicer.setMaximum(20.0)
        self.spinBoxWSlicer.setSingleStep(0.1)
        self.spinBoxWSlicer.setProperty("value", 1.0)
        self.spinBoxWSlicer.setObjectName("spinBoxWSlicer")
        self.gridLayout.addWidget(self.spinBoxWSlicer, 3, 3, 1, 1)
        self.spinBoxWZoom = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.spinBoxWZoom.setDecimals(1)
        self.spinBoxWZoom.setMaximum(20.0)
        self.spinBoxWZoom.setSingleStep(0.1)
        self.spinBoxWZoom.setProperty("value", 1.0)
        self.spinBoxWZoom.setObjectName("spinBoxWZoom")
        self.gridLayout.addWidget(self.spinBoxWZoom, 3, 4, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 6, 1, 2)
        self.spinBoxWSelect = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.spinBoxWSelect.setDecimals(1)
        self.spinBoxWSelect.setMaximum(20.0)
        self.spinBoxWSelect.setSingleStep(0.1)
        self.spinBoxWSelect.setProperty("value", 1.0)
        self.spinBoxWSelect.setObjectName("spinBoxWSelect")
        self.gridLayout.addWidget(self.spinBoxWSelect, 3, 8, 1, 1)
        self.comboBoxHSelect = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxHSelect.setObjectName("comboBoxHSelect")
        self.comboBoxHSelect.addItem("")
        self.comboBoxHSelect.addItem("")
        self.comboBoxHSelect.addItem("")
        self.comboBoxHSelect.addItem("")
        self.comboBoxHSelect.addItem("")
        self.comboBoxHSelect.addItem("")
        self.comboBoxHSelect.addItem("")
        self.comboBoxHSelect.addItem("")
        self.comboBoxHSelect.addItem("")
        self.comboBoxHSelect.addItem("")
        self.gridLayout.addWidget(self.comboBoxHSelect, 4, 8, 2, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 6, 2, 2)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 6, 1, 2)
        self.spinBoxASelect = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.spinBoxASelect.setDecimals(2)
        self.spinBoxASelect.setMaximum(1.0)
        self.spinBoxASelect.setSingleStep(0.05)
        self.spinBoxASelect.setProperty("value", 0.5)
        self.spinBoxASelect.setObjectName("spinBoxASelect")
        self.gridLayout.addWidget(self.spinBoxASelect, 6, 8, 1, 1)
        self.comboBoxCSelect = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxCSelect.setObjectName("comboBoxCSelect")
        self.comboBoxCSelect.addItem("")
        self.comboBoxCSelect.addItem("")
        self.comboBoxCSelect.addItem("")
        self.comboBoxCSelect.addItem("")
        self.comboBoxCSelect.addItem("")
        self.comboBoxCSelect.addItem("")
        self.gridLayout.addWidget(self.comboBoxCSelect, 1, 8, 1, 1)
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setLineWidth(0)
        self.line.setMidLineWidth(7)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 5, 6, 1)
        self.tabWidget.addTab(self.tab1, "")
        self.Tab2 = QtGui.QWidget()
        self.Tab2.setObjectName("Tab2")
        self.groupBox = QtGui.QGroupBox(self.Tab2)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 221, 201))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 198, 154))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 2)
        self.comboBoxMImage = QtGui.QComboBox(self.layoutWidget1)
        self.comboBoxMImage.setObjectName("comboBoxMImage")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.comboBoxMImage.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxMImage, 0, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget1)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 2)
        self.comboBoxIImage = QtGui.QComboBox(self.layoutWidget1)
        self.comboBoxIImage.setObjectName("comboBoxIImage")
        self.comboBoxIImage.addItem("")
        self.comboBoxIImage.addItem("")
        self.comboBoxIImage.addItem("")
        self.comboBoxIImage.addItem("")
        self.comboBoxIImage.addItem("")
        self.comboBoxIImage.addItem("")
        self.comboBoxIImage.addItem("")
        self.comboBoxIImage.addItem("")
        self.comboBoxIImage.addItem("")
        self.comboBoxIImage.addItem("")
        self.comboBoxIImage.addItem("")
        self.comboBoxIImage.addItem("")
        self.comboBoxIImage.addItem("")
        self.comboBoxIImage.addItem("")
        self.comboBoxIImage.addItem("")
        self.comboBoxIImage.addItem("")
        self.comboBoxIImage.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxIImage, 2, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget1)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 3, 0, 1, 2)
        self.spinBoxRImage = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.spinBoxRImage.setDecimals(1)
        self.spinBoxRImage.setSingleStep(0.1)
        self.spinBoxRImage.setProperty("value", 1.0)
        self.spinBoxRImage.setObjectName("spinBoxRImage")
        self.gridLayout_2.addWidget(self.spinBoxRImage, 3, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget1)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 4, 0, 1, 2)
        self.comboBoxSImage = QtGui.QComboBox(self.layoutWidget1)
        self.comboBoxSImage.setObjectName("comboBoxSImage")
        self.comboBoxSImage.addItem("")
        self.comboBoxSImage.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxSImage, 4, 2, 1, 1)
        self.checkBoxRmapImage = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBoxRmapImage.setObjectName("checkBoxRmapImage")
        self.gridLayout_2.addWidget(self.checkBoxRmapImage, 1, 1, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(self.Tab2)
        self.groupBox_2.setGeometry(QtCore.QRect(220, 10, 161, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 141, 151))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_15 = QtGui.QLabel(self.layoutWidget2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 2)
        self.comboBoxCMarker = QtGui.QComboBox(self.layoutWidget2)
        self.comboBoxCMarker.setObjectName("comboBoxCMarker")
        self.comboBoxCMarker.addItem("")
        self.comboBoxCMarker.addItem("")
        self.comboBoxCMarker.addItem("")
        self.comboBoxCMarker.addItem("")
        self.comboBoxCMarker.addItem("")
        self.comboBoxCMarker.addItem("")
        self.gridLayout_3.addWidget(self.comboBoxCMarker, 0, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 2)
        self.spinBoxWMarker = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.spinBoxWMarker.setDecimals(1)
        self.spinBoxWMarker.setMaximum(18.0)
        self.spinBoxWMarker.setSingleStep(0.1)
        self.spinBoxWMarker.setProperty("value", 1.0)
        self.spinBoxWMarker.setObjectName("spinBoxWMarker")
        self.gridLayout_3.addWidget(self.spinBoxWMarker, 1, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 2, 0, 1, 2)
        self.comboBoxHMarker = QtGui.QComboBox(self.layoutWidget2)
        self.comboBoxHMarker.setObjectName("comboBoxHMarker")
        self.comboBoxHMarker.addItem("")
        self.comboBoxHMarker.addItem("")
        self.comboBoxHMarker.addItem("")
        self.comboBoxHMarker.addItem("")
        self.comboBoxHMarker.addItem("")
        self.comboBoxHMarker.addItem("")
        self.comboBoxHMarker.addItem("")
        self.comboBoxHMarker.addItem("")
        self.comboBoxHMarker.addItem("")
        self.comboBoxHMarker.addItem("")
        self.gridLayout_3.addWidget(self.comboBoxHMarker, 2, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 3, 0, 1, 2)
        self.spinBoxAMarker = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.spinBoxAMarker.setMaximum(1.0)
        self.spinBoxAMarker.setSingleStep(0.1)
        self.spinBoxAMarker.setProperty("value", 0.5)
        self.spinBoxAMarker.setObjectName("spinBoxAMarker")
        self.gridLayout_3.addWidget(self.spinBoxAMarker, 3, 2, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.Tab2)
        self.groupBox_3.setGeometry(QtCore.QRect(380, 10, 171, 201))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 151, 151))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_19 = QtGui.QLabel(self.layoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 0, 0, 1, 2)
        self.comboBoxCSpaxSelect = QtGui.QComboBox(self.layoutWidget_2)
        self.comboBoxCSpaxSelect.setObjectName("comboBoxCSpaxSelect")
        self.comboBoxCSpaxSelect.addItem("")
        self.comboBoxCSpaxSelect.addItem("")
        self.comboBoxCSpaxSelect.addItem("")
        self.comboBoxCSpaxSelect.addItem("")
        self.comboBoxCSpaxSelect.addItem("")
        self.comboBoxCSpaxSelect.addItem("")
        self.gridLayout_4.addWidget(self.comboBoxCSpaxSelect, 0, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 1, 0, 1, 2)
        self.spinBoxWSpaxSelect = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.spinBoxWSpaxSelect.setDecimals(1)
        self.spinBoxWSpaxSelect.setMaximum(18.0)
        self.spinBoxWSpaxSelect.setSingleStep(0.1)
        self.spinBoxWSpaxSelect.setProperty("value", 1.0)
        self.spinBoxWSpaxSelect.setObjectName("spinBoxWSpaxSelect")
        self.gridLayout_4.addWidget(self.spinBoxWSpaxSelect, 1, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.layoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 2, 0, 1, 2)
        self.comboBoxHSpaxSelect = QtGui.QComboBox(self.layoutWidget_2)
        self.comboBoxHSpaxSelect.setObjectName("comboBoxHSpaxSelect")
        self.comboBoxHSpaxSelect.addItem("")
        self.comboBoxHSpaxSelect.addItem("")
        self.comboBoxHSpaxSelect.addItem("")
        self.comboBoxHSpaxSelect.addItem("")
        self.comboBoxHSpaxSelect.addItem("")
        self.comboBoxHSpaxSelect.addItem("")
        self.comboBoxHSpaxSelect.addItem("")
        self.comboBoxHSpaxSelect.addItem("")
        self.comboBoxHSpaxSelect.addItem("")
        self.comboBoxHSpaxSelect.addItem("")
        self.gridLayout_4.addWidget(self.comboBoxHSpaxSelect, 2, 2, 1, 1)
        self.label_22 = QtGui.QLabel(self.layoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 3, 0, 1, 2)
        self.spinBoxASpaxSelect = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.spinBoxASpaxSelect.setMaximum(1.0)
        self.spinBoxASpaxSelect.setSingleStep(0.1)
        self.spinBoxASpaxSelect.setProperty("value", 0.5)
        self.spinBoxASpaxSelect.setObjectName("spinBoxASpaxSelect")
        self.gridLayout_4.addWidget(self.spinBoxASpaxSelect, 3, 2, 1, 1)
        self.tabWidget.addTab(self.Tab2, "")
        self.Tab3 = QtGui.QWidget()
        self.Tab3.setObjectName("Tab3")
        self.groupBox_4 = QtGui.QGroupBox(self.Tab3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 161, 201))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget_3 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 30, 141, 151))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_23 = QtGui.QLabel(self.layoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 0, 0, 1, 2)
        self.comboBoxCQSOcont = QtGui.QComboBox(self.layoutWidget_3)
        self.comboBoxCQSOcont.setObjectName("comboBoxCQSOcont")
        self.comboBoxCQSOcont.addItem("")
        self.comboBoxCQSOcont.addItem("")
        self.comboBoxCQSOcont.addItem("")
        self.comboBoxCQSOcont.addItem("")
        self.comboBoxCQSOcont.addItem("")
        self.comboBoxCQSOcont.addItem("")
        self.gridLayout_5.addWidget(self.comboBoxCQSOcont, 0, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.layoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 1, 0, 1, 2)
        self.spinBoxWQSOcont = QtGui.QDoubleSpinBox(self.layoutWidget_3)
        self.spinBoxWQSOcont.setDecimals(1)
        self.spinBoxWQSOcont.setMaximum(18.0)
        self.spinBoxWQSOcont.setSingleStep(0.1)
        self.spinBoxWQSOcont.setProperty("value", 1.0)
        self.spinBoxWQSOcont.setObjectName("spinBoxWQSOcont")
        self.gridLayout_5.addWidget(self.spinBoxWQSOcont, 1, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.layoutWidget_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 2, 0, 1, 2)
        self.comboBoxHQSOcont = QtGui.QComboBox(self.layoutWidget_3)
        self.comboBoxHQSOcont.setObjectName("comboBoxHQSOcont")
        self.comboBoxHQSOcont.addItem("")
        self.comboBoxHQSOcont.addItem("")
        self.comboBoxHQSOcont.addItem("")
        self.comboBoxHQSOcont.addItem("")
        self.comboBoxHQSOcont.addItem("")
        self.comboBoxHQSOcont.addItem("")
        self.comboBoxHQSOcont.addItem("")
        self.comboBoxHQSOcont.addItem("")
        self.comboBoxHQSOcont.addItem("")
        self.comboBoxHQSOcont.addItem("")
        self.gridLayout_5.addWidget(self.comboBoxHQSOcont, 2, 2, 1, 1)
        self.label_26 = QtGui.QLabel(self.layoutWidget_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 3, 0, 1, 2)
        self.spinBoxAQSOcont = QtGui.QDoubleSpinBox(self.layoutWidget_3)
        self.spinBoxAQSOcont.setMaximum(1.0)
        self.spinBoxAQSOcont.setSingleStep(0.1)
        self.spinBoxAQSOcont.setProperty("value", 0.5)
        self.spinBoxAQSOcont.setObjectName("spinBoxAQSOcont")
        self.gridLayout_5.addWidget(self.spinBoxAQSOcont, 3, 2, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.Tab3)
        self.groupBox_5.setGeometry(QtCore.QRect(180, 10, 161, 201))
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget_4 = QtGui.QWidget(self.groupBox_5)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 30, 141, 151))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_27 = QtGui.QLabel(self.layoutWidget_4)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 0, 0, 1, 2)
        self.comboBoxCQSObroad = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBoxCQSObroad.setObjectName("comboBoxCQSObroad")
        self.comboBoxCQSObroad.addItem("")
        self.comboBoxCQSObroad.addItem("")
        self.comboBoxCQSObroad.addItem("")
        self.comboBoxCQSObroad.addItem("")
        self.comboBoxCQSObroad.addItem("")
        self.comboBoxCQSObroad.addItem("")
        self.gridLayout_6.addWidget(self.comboBoxCQSObroad, 0, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.layoutWidget_4)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 1, 0, 1, 2)
        self.spinBoxWQSObroad = QtGui.QDoubleSpinBox(self.layoutWidget_4)
        self.spinBoxWQSObroad.setDecimals(1)
        self.spinBoxWQSObroad.setMaximum(18.0)
        self.spinBoxWQSObroad.setSingleStep(0.1)
        self.spinBoxWQSObroad.setProperty("value", 1.0)
        self.spinBoxWQSObroad.setObjectName("spinBoxWQSObroad")
        self.gridLayout_6.addWidget(self.spinBoxWQSObroad, 1, 2, 1, 1)
        self.label_29 = QtGui.QLabel(self.layoutWidget_4)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 2, 0, 1, 2)
        self.comboBoxHQSObroad = QtGui.QComboBox(self.layoutWidget_4)
        self.comboBoxHQSObroad.setObjectName("comboBoxHQSObroad")
        self.comboBoxHQSObroad.addItem("")
        self.comboBoxHQSObroad.addItem("")
        self.comboBoxHQSObroad.addItem("")
        self.comboBoxHQSObroad.addItem("")
        self.comboBoxHQSObroad.addItem("")
        self.comboBoxHQSObroad.addItem("")
        self.comboBoxHQSObroad.addItem("")
        self.comboBoxHQSObroad.addItem("")
        self.comboBoxHQSObroad.addItem("")
        self.comboBoxHQSObroad.addItem("")
        self.gridLayout_6.addWidget(self.comboBoxHQSObroad, 2, 2, 1, 1)
        self.label_30 = QtGui.QLabel(self.layoutWidget_4)
        self.label_30.setObjectName("label_30")
        self.gridLayout_6.addWidget(self.label_30, 3, 0, 1, 2)
        self.spinBoxAQSObroad = QtGui.QDoubleSpinBox(self.layoutWidget_4)
        self.spinBoxAQSObroad.setMaximum(1.0)
        self.spinBoxAQSObroad.setSingleStep(0.1)
        self.spinBoxAQSObroad.setProperty("value", 0.5)
        self.spinBoxAQSObroad.setObjectName("spinBoxAQSObroad")
        self.gridLayout_6.addWidget(self.spinBoxAQSObroad, 3, 2, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.Tab3)
        self.groupBox_6.setGeometry(QtCore.QRect(350, 10, 161, 201))
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget_5 = QtGui.QWidget(self.groupBox_6)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 30, 141, 151))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_31 = QtGui.QLabel(self.layoutWidget_5)
        self.label_31.setObjectName("label_31")
        self.gridLayout_7.addWidget(self.label_31, 0, 0, 1, 2)
        self.comboBoxCQSOSpax = QtGui.QComboBox(self.layoutWidget_5)
        self.comboBoxCQSOSpax.setObjectName("comboBoxCQSOSpax")
        self.comboBoxCQSOSpax.addItem("")
        self.comboBoxCQSOSpax.addItem("")
        self.comboBoxCQSOSpax.addItem("")
        self.comboBoxCQSOSpax.addItem("")
        self.comboBoxCQSOSpax.addItem("")
        self.comboBoxCQSOSpax.addItem("")
        self.gridLayout_7.addWidget(self.comboBoxCQSOSpax, 0, 2, 1, 1)
        self.label_32 = QtGui.QLabel(self.layoutWidget_5)
        self.label_32.setObjectName("label_32")
        self.gridLayout_7.addWidget(self.label_32, 1, 0, 1, 2)
        self.spinBoxWQSOSpax = QtGui.QDoubleSpinBox(self.layoutWidget_5)
        self.spinBoxWQSOSpax.setDecimals(1)
        self.spinBoxWQSOSpax.setMaximum(18.0)
        self.spinBoxWQSOSpax.setSingleStep(0.1)
        self.spinBoxWQSOSpax.setProperty("value", 1.0)
        self.spinBoxWQSOSpax.setObjectName("spinBoxWQSOSpax")
        self.gridLayout_7.addWidget(self.spinBoxWQSOSpax, 1, 2, 1, 1)
        self.label_33 = QtGui.QLabel(self.layoutWidget_5)
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 2, 0, 1, 2)
        self.comboBoxHQSOSpax = QtGui.QComboBox(self.layoutWidget_5)
        self.comboBoxHQSOSpax.setObjectName("comboBoxHQSOSpax")
        self.comboBoxHQSOSpax.addItem("")
        self.comboBoxHQSOSpax.addItem("")
        self.comboBoxHQSOSpax.addItem("")
        self.comboBoxHQSOSpax.addItem("")
        self.comboBoxHQSOSpax.addItem("")
        self.comboBoxHQSOSpax.addItem("")
        self.comboBoxHQSOSpax.addItem("")
        self.comboBoxHQSOSpax.addItem("")
        self.comboBoxHQSOSpax.addItem("")
        self.comboBoxHQSOSpax.addItem("")
        self.gridLayout_7.addWidget(self.comboBoxHQSOSpax, 2, 2, 1, 1)
        self.label_34 = QtGui.QLabel(self.layoutWidget_5)
        self.label_34.setObjectName("label_34")
        self.gridLayout_7.addWidget(self.label_34, 3, 0, 1, 2)
        self.spinBoxAQSOSpax = QtGui.QDoubleSpinBox(self.layoutWidget_5)
        self.spinBoxAQSOSpax.setMaximum(1.0)
        self.spinBoxAQSOSpax.setSingleStep(0.1)
        self.spinBoxAQSOSpax.setProperty("value", 0.5)
        self.spinBoxAQSOSpax.setObjectName("spinBoxAQSOSpax")
        self.gridLayout_7.addWidget(self.spinBoxAQSOSpax, 3, 2, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.Tab3)
        self.groupBox_7.setGeometry(QtCore.QRect(520, 10, 161, 201))
        self.groupBox_7.setObjectName("groupBox_7")
        self.layoutWidget_6 = QtGui.QWidget(self.groupBox_7)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 30, 141, 151))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout_8 = QtGui.QGridLayout(self.layoutWidget_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_35 = QtGui.QLabel(self.layoutWidget_6)
        self.label_35.setObjectName("label_35")
        self.gridLayout_8.addWidget(self.label_35, 0, 0, 1, 2)
        self.comboBoxCEELRSpax = QtGui.QComboBox(self.layoutWidget_6)
        self.comboBoxCEELRSpax.setObjectName("comboBoxCEELRSpax")
        self.comboBoxCEELRSpax.addItem("")
        self.comboBoxCEELRSpax.addItem("")
        self.comboBoxCEELRSpax.addItem("")
        self.comboBoxCEELRSpax.addItem("")
        self.comboBoxCEELRSpax.addItem("")
        self.comboBoxCEELRSpax.addItem("")
        self.gridLayout_8.addWidget(self.comboBoxCEELRSpax, 0, 2, 1, 1)
        self.label_36 = QtGui.QLabel(self.layoutWidget_6)
        self.label_36.setObjectName("label_36")
        self.gridLayout_8.addWidget(self.label_36, 1, 0, 1, 2)
        self.spinBoxWEELRSpax = QtGui.QDoubleSpinBox(self.layoutWidget_6)
        self.spinBoxWEELRSpax.setDecimals(1)
        self.spinBoxWEELRSpax.setMaximum(18.0)
        self.spinBoxWEELRSpax.setSingleStep(0.1)
        self.spinBoxWEELRSpax.setProperty("value", 1.0)
        self.spinBoxWEELRSpax.setObjectName("spinBoxWEELRSpax")
        self.gridLayout_8.addWidget(self.spinBoxWEELRSpax, 1, 2, 1, 1)
        self.label_37 = QtGui.QLabel(self.layoutWidget_6)
        self.label_37.setObjectName("label_37")
        self.gridLayout_8.addWidget(self.label_37, 2, 0, 1, 2)
        self.comboBoxHEELRSpax = QtGui.QComboBox(self.layoutWidget_6)
        self.comboBoxHEELRSpax.setObjectName("comboBoxHEELRSpax")
        self.comboBoxHEELRSpax.addItem("")
        self.comboBoxHEELRSpax.addItem("")
        self.comboBoxHEELRSpax.addItem("")
        self.comboBoxHEELRSpax.addItem("")
        self.comboBoxHEELRSpax.addItem("")
        self.comboBoxHEELRSpax.addItem("")
        self.comboBoxHEELRSpax.addItem("")
        self.comboBoxHEELRSpax.addItem("")
        self.comboBoxHEELRSpax.addItem("")
        self.comboBoxHEELRSpax.addItem("")
        self.gridLayout_8.addWidget(self.comboBoxHEELRSpax, 2, 2, 1, 1)
        self.label_38 = QtGui.QLabel(self.layoutWidget_6)
        self.label_38.setObjectName("label_38")
        self.gridLayout_8.addWidget(self.label_38, 3, 0, 1, 2)
        self.spinBoxAEELRSpax = QtGui.QDoubleSpinBox(self.layoutWidget_6)
        self.spinBoxAEELRSpax.setMaximum(1.0)
        self.spinBoxAEELRSpax.setSingleStep(0.1)
        self.spinBoxAEELRSpax.setProperty("value", 0.5)
        self.spinBoxAEELRSpax.setObjectName("spinBoxAEELRSpax")
        self.gridLayout_8.addWidget(self.spinBoxAEELRSpax, 3, 2, 1, 1)
        self.tabWidget.addTab(self.Tab3, "")

        self.retranslateUi(dlgColorProperties)
        self.tabWidget.setCurrentIndex(0)
        self.comboBoxMImage.setCurrentIndex(10)
        self.comboBoxHSpaxSelect.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(dlgColorProperties)

    def retranslateUi(self, dlgColorProperties):
        dlgColorProperties.setWindowTitle(QtGui.QApplication.translate("dlgColorProperties", "Color Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("dlgColorProperties", "Spectrum 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("dlgColorProperties", "Spectrum 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("dlgColorProperties", "Slice Marker", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("dlgColorProperties", "Zoom Window", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("dlgColorProperties", " Select Region", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("dlgColorProperties", "Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSpec1.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSpec1.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSpec1.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSpec1.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSpec1.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSpec1.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSpec2.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSpec2.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSpec2.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSpec2.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSpec2.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSpec2.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSlicer.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSlicer.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSlicer.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSlicer.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSlicer.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSlicer.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCZoom.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCZoom.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCZoom.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCZoom.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCZoom.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCZoom.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("dlgColorProperties", "Line Style:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSSpec1.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "solid", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSSpec1.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "dashed", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSSpec1.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "dotted", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSSpec1.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "dash-dot", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSSpec2.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "solid", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSSpec2.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "dashed", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSSpec2.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "dotted", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSSpec2.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "dash-dot", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSSlicer.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "solid", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSSlicer.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "dashed", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSSlicer.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "dotted", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSSlicer.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "dash-dot", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSZoom.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "solid", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSZoom.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "dashed", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSZoom.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "dotted", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSZoom.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "dash-dot", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSSelect.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "solid", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSSelect.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "dashed", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSSelect.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "dotted", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSSelect.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "dash-dot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("dlgColorProperties", "Line Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSelect.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSelect.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSelect.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "|", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSelect.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSelect.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSelect.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSelect.setItemText(6, QtGui.QApplication.translate("dlgColorProperties", "o", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSelect.setItemText(7, QtGui.QApplication.translate("dlgColorProperties", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSelect.setItemText(8, QtGui.QApplication.translate("dlgColorProperties", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSelect.setItemText(9, QtGui.QApplication.translate("dlgColorProperties", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("dlgColorProperties", "Hatch:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("dlgColorProperties", "Alpha:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSelect.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSelect.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSelect.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSelect.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSelect.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSelect.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), QtGui.QApplication.translate("dlgColorProperties", "Sp&ectral Widget", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("dlgColorProperties", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("dlgColorProperties", "Colormap:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "gray", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "spectral", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "Greys", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "RdBu", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "Spectral", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "Accent", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(6, QtGui.QApplication.translate("dlgColorProperties", "Blues", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(7, QtGui.QApplication.translate("dlgColorProperties", "afmhot", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(8, QtGui.QApplication.translate("dlgColorProperties", "gist_gray", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(9, QtGui.QApplication.translate("dlgColorProperties", "gist_heat", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(10, QtGui.QApplication.translate("dlgColorProperties", "hot", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(11, QtGui.QApplication.translate("dlgColorProperties", "hsv", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(12, QtGui.QApplication.translate("dlgColorProperties", "jet", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(13, QtGui.QApplication.translate("dlgColorProperties", "BrBG", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(14, QtGui.QApplication.translate("dlgColorProperties", "BuGn", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(15, QtGui.QApplication.translate("dlgColorProperties", "BuPu", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(16, QtGui.QApplication.translate("dlgColorProperties", "Dark2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(17, QtGui.QApplication.translate("dlgColorProperties", "GnBu", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(18, QtGui.QApplication.translate("dlgColorProperties", "Greens", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(19, QtGui.QApplication.translate("dlgColorProperties", "OrRd", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(20, QtGui.QApplication.translate("dlgColorProperties", "Oranges", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(21, QtGui.QApplication.translate("dlgColorProperties", "PRGn", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(22, QtGui.QApplication.translate("dlgColorProperties", "Paired", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(23, QtGui.QApplication.translate("dlgColorProperties", "Pastel1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(24, QtGui.QApplication.translate("dlgColorProperties", "Pastel2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(25, QtGui.QApplication.translate("dlgColorProperties", "PiYG", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(26, QtGui.QApplication.translate("dlgColorProperties", "PuBu", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(27, QtGui.QApplication.translate("dlgColorProperties", "PuBuGn", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(28, QtGui.QApplication.translate("dlgColorProperties", "PuOr", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(29, QtGui.QApplication.translate("dlgColorProperties", "PuRd", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(30, QtGui.QApplication.translate("dlgColorProperties", "Purples", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(31, QtGui.QApplication.translate("dlgColorProperties", "RdYIBu", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(32, QtGui.QApplication.translate("dlgColorProperties", "RdYIGn", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(33, QtGui.QApplication.translate("dlgColorProperties", "Reds", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(34, QtGui.QApplication.translate("dlgColorProperties", "Set1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(35, QtGui.QApplication.translate("dlgColorProperties", "Set2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(36, QtGui.QApplication.translate("dlgColorProperties", "Set3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(37, QtGui.QApplication.translate("dlgColorProperties", "YIGn", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(38, QtGui.QApplication.translate("dlgColorProperties", "YIGnBu", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(39, QtGui.QApplication.translate("dlgColorProperties", "YIOrBr", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(40, QtGui.QApplication.translate("dlgColorProperties", "YIOrRd", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(41, QtGui.QApplication.translate("dlgColorProperties", "autumn", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(42, QtGui.QApplication.translate("dlgColorProperties", "binary", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(43, QtGui.QApplication.translate("dlgColorProperties", "bone", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(44, QtGui.QApplication.translate("dlgColorProperties", "brg", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(45, QtGui.QApplication.translate("dlgColorProperties", "bwr", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(46, QtGui.QApplication.translate("dlgColorProperties", "cool", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(47, QtGui.QApplication.translate("dlgColorProperties", "cooper", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(48, QtGui.QApplication.translate("dlgColorProperties", "flag", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(49, QtGui.QApplication.translate("dlgColorProperties", "gist_earth", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(50, QtGui.QApplication.translate("dlgColorProperties", "gist_ncar", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(51, QtGui.QApplication.translate("dlgColorProperties", "gist_rainbow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(52, QtGui.QApplication.translate("dlgColorProperties", "gist_stern", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(53, QtGui.QApplication.translate("dlgColorProperties", "gist_yarg", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(54, QtGui.QApplication.translate("dlgColorProperties", "gnuplot", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(55, QtGui.QApplication.translate("dlgColorProperties", "gnuplot2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(56, QtGui.QApplication.translate("dlgColorProperties", "ocean", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(57, QtGui.QApplication.translate("dlgColorProperties", "pink", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(58, QtGui.QApplication.translate("dlgColorProperties", "prism", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(59, QtGui.QApplication.translate("dlgColorProperties", "rainbow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(60, QtGui.QApplication.translate("dlgColorProperties", "seismic", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(61, QtGui.QApplication.translate("dlgColorProperties", "spring", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(62, QtGui.QApplication.translate("dlgColorProperties", "summer", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(63, QtGui.QApplication.translate("dlgColorProperties", "terrain", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMImage.setItemText(64, QtGui.QApplication.translate("dlgColorProperties", "winter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("dlgColorProperties", "Interpolation:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxIImage.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "nearest", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxIImage.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "bilinear", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxIImage.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "bicubic", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxIImage.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "spline16", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxIImage.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "spline36", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxIImage.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "hanning", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxIImage.setItemText(6, QtGui.QApplication.translate("dlgColorProperties", "hamming", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxIImage.setItemText(7, QtGui.QApplication.translate("dlgColorProperties", "hermite", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxIImage.setItemText(8, QtGui.QApplication.translate("dlgColorProperties", "kaiser", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxIImage.setItemText(9, QtGui.QApplication.translate("dlgColorProperties", "quadradic", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxIImage.setItemText(10, QtGui.QApplication.translate("dlgColorProperties", "catrom", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxIImage.setItemText(11, QtGui.QApplication.translate("dlgColorProperties", "gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxIImage.setItemText(12, QtGui.QApplication.translate("dlgColorProperties", "bessel", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxIImage.setItemText(13, QtGui.QApplication.translate("dlgColorProperties", "mitchell", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxIImage.setItemText(14, QtGui.QApplication.translate("dlgColorProperties", "sinc", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxIImage.setItemText(15, QtGui.QApplication.translate("dlgColorProperties", "lanczos", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxIImage.setItemText(16, QtGui.QApplication.translate("dlgColorProperties", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("dlgColorProperties", "Filter radius:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("dlgColorProperties", "Scaling:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSImage.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSImage.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "Logarithmic", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxRmapImage.setText(QtGui.QApplication.translate("dlgColorProperties", "reversed map", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("dlgColorProperties", "Spaxel marker", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("dlgColorProperties", "Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCMarker.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCMarker.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCMarker.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCMarker.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCMarker.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCMarker.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("dlgColorProperties", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("dlgColorProperties", "Hatch:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHMarker.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHMarker.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHMarker.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "|", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHMarker.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHMarker.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHMarker.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHMarker.setItemText(6, QtGui.QApplication.translate("dlgColorProperties", "o", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHMarker.setItemText(7, QtGui.QApplication.translate("dlgColorProperties", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHMarker.setItemText(8, QtGui.QApplication.translate("dlgColorProperties", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHMarker.setItemText(9, QtGui.QApplication.translate("dlgColorProperties", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("dlgColorProperties", "Alpha:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("dlgColorProperties", "Spaxel Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("dlgColorProperties", "Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSpaxSelect.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSpaxSelect.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSpaxSelect.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSpaxSelect.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSpaxSelect.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCSpaxSelect.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("dlgColorProperties", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("dlgColorProperties", "Hatch:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSpaxSelect.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSpaxSelect.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSpaxSelect.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "|", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSpaxSelect.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSpaxSelect.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSpaxSelect.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSpaxSelect.setItemText(6, QtGui.QApplication.translate("dlgColorProperties", "o", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSpaxSelect.setItemText(7, QtGui.QApplication.translate("dlgColorProperties", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSpaxSelect.setItemText(8, QtGui.QApplication.translate("dlgColorProperties", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHSpaxSelect.setItemText(9, QtGui.QApplication.translate("dlgColorProperties", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("dlgColorProperties", "Alpha:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab2), QtGui.QApplication.translate("dlgColorProperties", "Sp&axel Widget", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("dlgColorProperties", "QSO continuum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("dlgColorProperties", "Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCQSOcont.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCQSOcont.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCQSOcont.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCQSOcont.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCQSOcont.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCQSOcont.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("dlgColorProperties", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("dlgColorProperties", "Hatch:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOcont.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOcont.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOcont.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "|", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOcont.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOcont.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOcont.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOcont.setItemText(6, QtGui.QApplication.translate("dlgColorProperties", "o", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOcont.setItemText(7, QtGui.QApplication.translate("dlgColorProperties", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOcont.setItemText(8, QtGui.QApplication.translate("dlgColorProperties", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOcont.setItemText(9, QtGui.QApplication.translate("dlgColorProperties", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("dlgColorProperties", "Alpha:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("dlgColorProperties", "QSO Broad Line", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("dlgColorProperties", "Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCQSObroad.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCQSObroad.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCQSObroad.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCQSObroad.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCQSObroad.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCQSObroad.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("dlgColorProperties", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("dlgColorProperties", "Hatch:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSObroad.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSObroad.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSObroad.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "|", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSObroad.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSObroad.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSObroad.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSObroad.setItemText(6, QtGui.QApplication.translate("dlgColorProperties", "o", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSObroad.setItemText(7, QtGui.QApplication.translate("dlgColorProperties", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSObroad.setItemText(8, QtGui.QApplication.translate("dlgColorProperties", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSObroad.setItemText(9, QtGui.QApplication.translate("dlgColorProperties", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("dlgColorProperties", "Alpha:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("dlgColorProperties", "QSO Spaxels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("dlgColorProperties", "Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCQSOSpax.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCQSOSpax.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCQSOSpax.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCQSOSpax.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCQSOSpax.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCQSOSpax.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("dlgColorProperties", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("dlgColorProperties", "Hatch:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOSpax.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOSpax.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOSpax.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "|", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOSpax.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOSpax.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOSpax.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOSpax.setItemText(6, QtGui.QApplication.translate("dlgColorProperties", "o", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOSpax.setItemText(7, QtGui.QApplication.translate("dlgColorProperties", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOSpax.setItemText(8, QtGui.QApplication.translate("dlgColorProperties", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHQSOSpax.setItemText(9, QtGui.QApplication.translate("dlgColorProperties", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("dlgColorProperties", "Alpha:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("dlgColorProperties", "EELR Spaxels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("dlgColorProperties", "Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCEELRSpax.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCEELRSpax.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCEELRSpax.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCEELRSpax.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCEELRSpax.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCEELRSpax.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("dlgColorProperties", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("dlgColorProperties", "Hatch:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHEELRSpax.setItemText(0, QtGui.QApplication.translate("dlgColorProperties", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHEELRSpax.setItemText(1, QtGui.QApplication.translate("dlgColorProperties", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHEELRSpax.setItemText(2, QtGui.QApplication.translate("dlgColorProperties", "|", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHEELRSpax.setItemText(3, QtGui.QApplication.translate("dlgColorProperties", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHEELRSpax.setItemText(4, QtGui.QApplication.translate("dlgColorProperties", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHEELRSpax.setItemText(5, QtGui.QApplication.translate("dlgColorProperties", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHEELRSpax.setItemText(6, QtGui.QApplication.translate("dlgColorProperties", "o", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHEELRSpax.setItemText(7, QtGui.QApplication.translate("dlgColorProperties", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHEELRSpax.setItemText(8, QtGui.QApplication.translate("dlgColorProperties", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxHEELRSpax.setItemText(9, QtGui.QApplication.translate("dlgColorProperties", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("dlgColorProperties", "Alpha:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab3), QtGui.QApplication.translate("dlgColorProperties", "QSO &Regions", None, QtGui.QApplication.UnicodeUTF8))

