# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './mainwindow.ui'
#
# Created: Fri Jan  7 21:48:00 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1238, 680)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_61 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_61.addWidget(self.line)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_26 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalLayout_57 = QtGui.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.labelFileIn = QtGui.QLabel(self.layoutWidget)
        self.labelFileIn.setObjectName("labelFileIn")
        self.horizontalLayout_57.addWidget(self.labelFileIn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_57.addItem(spacerItem)
        self.verticalLayout_26.addLayout(self.horizontalLayout_57)
        self.lineCubeIn = QtGui.QLineEdit(self.layoutWidget)
        self.lineCubeIn.setEnabled(False)
        self.lineCubeIn.setReadOnly(True)
        self.lineCubeIn.setObjectName("lineCubeIn")
        self.verticalLayout_26.addWidget(self.lineCubeIn)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.line_2 = QtGui.QFrame(self.layoutWidget1)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_25.addWidget(self.line_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem1)
        self.groupBoxSelectRegions = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBoxSelectRegions.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBoxSelectRegions.setFont(font)
        self.groupBoxSelectRegions.setAutoFillBackground(False)
        self.groupBoxSelectRegions.setFlat(False)
        self.groupBoxSelectRegions.setCheckable(False)
        self.groupBoxSelectRegions.setObjectName("groupBoxSelectRegions")
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.groupBoxSelectRegions)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButtonRegionRegular = QtGui.QRadioButton(self.groupBoxSelectRegions)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.radioButtonRegionRegular.setFont(font)
        self.radioButtonRegionRegular.setChecked(True)
        self.radioButtonRegionRegular.setObjectName("radioButtonRegionRegular")
        self.horizontalLayout_8.addWidget(self.radioButtonRegionRegular)
        spacerItem2 = QtGui.QSpacerItem(98, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.label_2 = QtGui.QLabel(self.groupBoxSelectRegions)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.spinBoxQSORegionSize = QtGui.QSpinBox(self.groupBoxSelectRegions)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxQSORegionSize.setFont(font)
        self.spinBoxQSORegionSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxQSORegionSize.setMinimum(1)
        self.spinBoxQSORegionSize.setMaximum(1000)
        self.spinBoxQSORegionSize.setSingleStep(2)
        self.spinBoxQSORegionSize.setObjectName("spinBoxQSORegionSize")
        self.horizontalLayout_4.addWidget(self.spinBoxQSORegionSize)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtGui.QSpacerItem(28, 26, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.label_3 = QtGui.QLabel(self.groupBoxSelectRegions)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.spinBoxEELRRegionWidth = QtGui.QSpinBox(self.groupBoxSelectRegions)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxEELRRegionWidth.setFont(font)
        self.spinBoxEELRRegionWidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxEELRRegionWidth.setMinimum(1)
        self.spinBoxEELRRegionWidth.setMaximum(1000)
        self.spinBoxEELRRegionWidth.setObjectName("spinBoxEELRRegionWidth")
        self.horizontalLayout_7.addWidget(self.spinBoxEELRRegionWidth)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_15.addLayout(self.verticalLayout_4)
        spacerItem5 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButtonRegionManual = QtGui.QRadioButton(self.groupBoxSelectRegions)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.radioButtonRegionManual.setFont(font)
        self.radioButtonRegionManual.setObjectName("radioButtonRegionManual")
        self.horizontalLayout_5.addWidget(self.radioButtonRegionManual)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtGui.QLabel(self.groupBoxSelectRegions)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.buttonQSOSaveMask = QtGui.QPushButton(self.groupBoxSelectRegions)
        self.buttonQSOSaveMask.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.buttonQSOSaveMask.setFont(font)
        self.buttonQSOSaveMask.setObjectName("buttonQSOSaveMask")
        self.horizontalLayout_9.addWidget(self.buttonQSOSaveMask)
        self.buttonQSOChangeMask = QtGui.QPushButton(self.groupBoxSelectRegions)
        self.buttonQSOChangeMask.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.buttonQSOChangeMask.setFont(font)
        self.buttonQSOChangeMask.setObjectName("buttonQSOChangeMask")
        self.horizontalLayout_9.addWidget(self.buttonQSOChangeMask)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtGui.QLabel(self.groupBoxSelectRegions)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.buttonEELRSaveMask = QtGui.QPushButton(self.groupBoxSelectRegions)
        self.buttonEELRSaveMask.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.buttonEELRSaveMask.setFont(font)
        self.buttonEELRSaveMask.setObjectName("buttonEELRSaveMask")
        self.horizontalLayout_10.addWidget(self.buttonEELRSaveMask)
        self.buttonEELRChangeMask = QtGui.QPushButton(self.groupBoxSelectRegions)
        self.buttonEELRChangeMask.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.buttonEELRChangeMask.setFont(font)
        self.buttonEELRChangeMask.setObjectName("buttonEELRChangeMask")
        self.horizontalLayout_10.addWidget(self.buttonEELRChangeMask)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_15.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.checkBoxDisplayMask = QtGui.QCheckBox(self.groupBoxSelectRegions)
        self.checkBoxDisplayMask.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.checkBoxDisplayMask.setFont(font)
        self.checkBoxDisplayMask.setCheckable(True)
        self.checkBoxDisplayMask.setChecked(False)
        self.checkBoxDisplayMask.setObjectName("checkBoxDisplayMask")
        self.horizontalLayout_6.addWidget(self.checkBoxDisplayMask)
        spacerItem8 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_25.addLayout(self.verticalLayout_7)
        self.verticalLayout_25.addWidget(self.groupBoxSelectRegions)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.groupBoxSpecRegions = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBoxSpecRegions.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBoxSpecRegions.setFont(font)
        self.groupBoxSpecRegions.setObjectName("groupBoxSpecRegions")
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.groupBoxSpecRegions)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem9 = QtGui.QSpacerItem(68, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem9)
        self.comboBoxRegions = QtGui.QComboBox(self.groupBoxSpecRegions)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.comboBoxRegions.setFont(font)
        self.comboBoxRegions.setObjectName("comboBoxRegions")
        self.comboBoxRegions.addItem("")
        self.comboBoxRegions.addItem("")
        self.comboBoxRegions.addItem("")
        self.comboBoxRegions.addItem("")
        self.horizontalLayout_16.addWidget(self.comboBoxRegions)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtGui.QLabel(self.groupBoxSpecRegions)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.buttonSaveBroad1 = QtGui.QPushButton(self.groupBoxSpecRegions)
        self.buttonSaveBroad1.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.buttonSaveBroad1.setFont(font)
        self.buttonSaveBroad1.setObjectName("buttonSaveBroad1")
        self.horizontalLayout_11.addWidget(self.buttonSaveBroad1)
        self.buttonChangeBroad1 = QtGui.QPushButton(self.groupBoxSpecRegions)
        self.buttonChangeBroad1.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.buttonChangeBroad1.setFont(font)
        self.buttonChangeBroad1.setObjectName("buttonChangeBroad1")
        self.horizontalLayout_11.addWidget(self.buttonChangeBroad1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtGui.QLabel(self.groupBoxSpecRegions)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.buttonSaveBroad2 = QtGui.QPushButton(self.groupBoxSpecRegions)
        self.buttonSaveBroad2.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.buttonSaveBroad2.setFont(font)
        self.buttonSaveBroad2.setObjectName("buttonSaveBroad2")
        self.horizontalLayout_12.addWidget(self.buttonSaveBroad2)
        self.buttonChangeBroad2 = QtGui.QPushButton(self.groupBoxSpecRegions)
        self.buttonChangeBroad2.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.buttonChangeBroad2.setFont(font)
        self.buttonChangeBroad2.setObjectName("buttonChangeBroad2")
        self.horizontalLayout_12.addWidget(self.buttonChangeBroad2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtGui.QLabel(self.groupBoxSpecRegions)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.buttonSaveCont1 = QtGui.QPushButton(self.groupBoxSpecRegions)
        self.buttonSaveCont1.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.buttonSaveCont1.setFont(font)
        self.buttonSaveCont1.setObjectName("buttonSaveCont1")
        self.horizontalLayout_13.addWidget(self.buttonSaveCont1)
        self.buttonChangeCont1 = QtGui.QPushButton(self.groupBoxSpecRegions)
        self.buttonChangeCont1.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.buttonChangeCont1.setFont(font)
        self.buttonChangeCont1.setObjectName("buttonChangeCont1")
        self.horizontalLayout_13.addWidget(self.buttonChangeCont1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtGui.QLabel(self.groupBoxSpecRegions)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.buttonSaveCont2 = QtGui.QPushButton(self.groupBoxSpecRegions)
        self.buttonSaveCont2.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.buttonSaveCont2.setFont(font)
        self.buttonSaveCont2.setObjectName("buttonSaveCont2")
        self.horizontalLayout_14.addWidget(self.buttonSaveCont2)
        self.buttonChangeCont2 = QtGui.QPushButton(self.groupBoxSpecRegions)
        self.buttonChangeCont2.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.buttonChangeCont2.setFont(font)
        self.buttonChangeCont2.setObjectName("buttonChangeCont2")
        self.horizontalLayout_14.addWidget(self.buttonChangeCont2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBoxInterpCont = QtGui.QCheckBox(self.groupBoxSpecRegions)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.checkBoxInterpCont.setFont(font)
        self.checkBoxInterpCont.setObjectName("checkBoxInterpCont")
        self.verticalLayout_6.addWidget(self.checkBoxInterpCont)
        self.checkBoxShowRegion = QtGui.QCheckBox(self.groupBoxSpecRegions)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.checkBoxShowRegion.setFont(font)
        self.checkBoxShowRegion.setObjectName("checkBoxShowRegion")
        self.verticalLayout_6.addWidget(self.checkBoxShowRegion)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.horizontalLayout_28.addLayout(self.verticalLayout_8)
        self.horizontalLayout_30.addWidget(self.groupBoxSpecRegions)
        self.groupBoxMethod = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBoxMethod.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBoxMethod.setFont(font)
        self.groupBoxMethod.setObjectName("groupBoxMethod")
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.groupBoxMethod)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label = QtGui.QLabel(self.groupBoxMethod)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_19.addWidget(self.label)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem10)
        self.verticalLayout_10.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem11 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem11)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.comboBoxCorrMode = QtGui.QComboBox(self.groupBoxMethod)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.comboBoxCorrMode.setFont(font)
        self.comboBoxCorrMode.setObjectName("comboBoxCorrMode")
        self.comboBoxCorrMode.addItem("")
        self.comboBoxCorrMode.addItem("")
        self.comboBoxCorrMode.addItem("")
        self.comboBoxCorrMode.addItem("")
        self.verticalLayout_9.addWidget(self.comboBoxCorrMode)
        spacerItem12 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem12)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_15 = QtGui.QLabel(self.groupBoxMethod)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_17.addWidget(self.label_15)
        self.lineEditSFBFactor = QtGui.QLineEdit(self.groupBoxMethod)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lineEditSFBFactor.setFont(font)
        self.lineEditSFBFactor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditSFBFactor.setObjectName("lineEditSFBFactor")
        self.horizontalLayout_17.addWidget(self.lineEditSFBFactor)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.pushButtonEditHostModel = QtGui.QPushButton(self.groupBoxMethod)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pushButtonEditHostModel.setFont(font)
        self.pushButtonEditHostModel.setObjectName("pushButtonEditHostModel")
        self.verticalLayout_9.addWidget(self.pushButtonEditHostModel)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_4 = QtGui.QLabel(self.groupBoxMethod)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_18.addWidget(self.label_4)
        self.spinBoxIterations = QtGui.QSpinBox(self.groupBoxMethod)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxIterations.setFont(font)
        self.spinBoxIterations.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxIterations.setMinimum(1)
        self.spinBoxIterations.setObjectName("spinBoxIterations")
        self.horizontalLayout_18.addWidget(self.spinBoxIterations)
        self.verticalLayout_9.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_20.addLayout(self.verticalLayout_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_20)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        spacerItem13 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem13)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_16 = QtGui.QLabel(self.groupBoxMethod)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_21.addWidget(self.label_16)
        self.comboBoxRegionMeasure = QtGui.QComboBox(self.groupBoxMethod)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.comboBoxRegionMeasure.setFont(font)
        self.comboBoxRegionMeasure.setObjectName("comboBoxRegionMeasure")
        self.comboBoxRegionMeasure.addItem("")
        self.comboBoxRegionMeasure.addItem("")
        self.comboBoxRegionMeasure.addItem("")
        self.horizontalLayout_21.addWidget(self.comboBoxRegionMeasure)
        self.verticalLayout_11.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.radioButtonRadius = QtGui.QRadioButton(self.groupBoxMethod)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.radioButtonRadius.setFont(font)
        self.radioButtonRadius.setObjectName("radioButtonRadius")
        self.horizontalLayout_23.addWidget(self.radioButtonRadius)
        self.lineEditRadius = QtGui.QLineEdit(self.groupBoxMethod)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lineEditRadius.setFont(font)
        self.lineEditRadius.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditRadius.setObjectName("lineEditRadius")
        self.horizontalLayout_23.addWidget(self.lineEditRadius)
        self.verticalLayout_11.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_29.addLayout(self.verticalLayout_11)
        self.horizontalLayout_30.addWidget(self.groupBoxMethod)
        self.verticalLayout_14.addLayout(self.horizontalLayout_30)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem14)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.pushButtonStartSubtract = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonStartSubtract.setObjectName("pushButtonStartSubtract")
        self.horizontalLayout_24.addWidget(self.pushButtonStartSubtract)
        self.pushButtonSaveResults = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonSaveResults.setEnabled(False)
        self.pushButtonSaveResults.setObjectName("pushButtonSaveResults")
        self.horizontalLayout_24.addWidget(self.pushButtonSaveResults)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_24)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem15)
        self.verticalLayout_14.addLayout(self.horizontalLayout_31)
        self.verticalLayout_25.addLayout(self.verticalLayout_14)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem16)
        self.horizontalLayout_61.addWidget(self.splitter)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_61.addWidget(self.line_4)
        self.horizontalLayout_60 = QtGui.QHBoxLayout()
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.verticalLayout_29 = QtGui.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.verticalLayout_28 = QtGui.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        spacerItem17 = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_28.addItem(spacerItem17)
        self.horizontalLayout_59 = QtGui.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_12.addWidget(self.label_7)
        self.lineEditMaxImg = QtGui.QLineEdit(self.centralwidget)
        self.lineEditMaxImg.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMaxImg.sizePolicy().hasHeightForWidth())
        self.lineEditMaxImg.setSizePolicy(sizePolicy)
        self.lineEditMaxImg.setObjectName("lineEditMaxImg")
        self.verticalLayout_12.addWidget(self.lineEditMaxImg)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_12.addWidget(self.label_8)
        self.lineEditMinImg = QtGui.QLineEdit(self.centralwidget)
        self.lineEditMinImg.setEnabled(False)
        self.lineEditMinImg.setObjectName("lineEditMinImg")
        self.verticalLayout_12.addWidget(self.lineEditMinImg)
        self.checkBoxAutoImg = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxAutoImg.setEnabled(False)
        self.checkBoxAutoImg.setAcceptDrops(False)
        self.checkBoxAutoImg.setChecked(True)
        self.checkBoxAutoImg.setObjectName("checkBoxAutoImg")
        self.verticalLayout_12.addWidget(self.checkBoxAutoImg)
        self.horizontalLayout_59.addLayout(self.verticalLayout_12)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_59.addItem(spacerItem18)
        self.verticalLayout_28.addLayout(self.horizontalLayout_59)
        spacerItem19 = QtGui.QSpacerItem(20, 198, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_28.addItem(spacerItem19)
        self.verticalLayout_29.addLayout(self.verticalLayout_28)
        self.verticalLayout_27 = QtGui.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.horizontalLayout_58 = QtGui.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.lineEditMaxSpec = QtGui.QLineEdit(self.centralwidget)
        self.lineEditMaxSpec.setEnabled(False)
        self.lineEditMaxSpec.setObjectName("lineEditMaxSpec")
        self.verticalLayout.addWidget(self.lineEditMaxSpec)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lineEditMinSpec = QtGui.QLineEdit(self.centralwidget)
        self.lineEditMinSpec.setEnabled(False)
        self.lineEditMinSpec.setObjectName("lineEditMinSpec")
        self.verticalLayout.addWidget(self.lineEditMinSpec)
        self.checkBoxAutoSpec = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxAutoSpec.setEnabled(False)
        self.checkBoxAutoSpec.setAcceptDrops(False)
        self.checkBoxAutoSpec.setChecked(True)
        self.checkBoxAutoSpec.setObjectName("checkBoxAutoSpec")
        self.verticalLayout.addWidget(self.checkBoxAutoSpec)
        self.horizontalLayout_58.addLayout(self.verticalLayout)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_58.addItem(spacerItem20)
        self.verticalLayout_27.addLayout(self.horizontalLayout_58)
        spacerItem21 = QtGui.QSpacerItem(20, 168, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_27.addItem(spacerItem21)
        self.verticalLayout_29.addLayout(self.verticalLayout_27)
        self.horizontalLayout_60.addLayout(self.verticalLayout_29)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem22)
        self.label_17 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_26.addWidget(self.label_17)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem23)
        self.gridLayout.addLayout(self.horizontalLayout_26, 0, 0, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem24, 0, 1, 2, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_18 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout.addWidget(self.label_18)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.radioButtonHost = QtGui.QRadioButton(self.centralwidget)
        self.radioButtonHost.setEnabled(False)
        self.radioButtonHost.setChecked(True)
        self.radioButtonHost.setObjectName("radioButtonHost")
        self.horizontalLayout_22.addWidget(self.radioButtonHost)
        self.radioButtonQSO = QtGui.QRadioButton(self.centralwidget)
        self.radioButtonQSO.setEnabled(False)
        self.radioButtonQSO.setIconSize(QtCore.QSize(10, 10))
        self.radioButtonQSO.setObjectName("radioButtonQSO")
        self.horizontalLayout_22.addWidget(self.radioButtonQSO)
        self.horizontalLayout.addLayout(self.horizontalLayout_22)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 2, 2, 1)
        self.inputSpaxelWidget = MatplotlibImgWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputSpaxelWidget.sizePolicy().hasHeightForWidth())
        self.inputSpaxelWidget.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(126, 29, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 29, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 29, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        self.inputSpaxelWidget.setPalette(palette)
        self.inputSpaxelWidget.setObjectName("inputSpaxelWidget")
        self.gridLayout.addWidget(self.inputSpaxelWidget, 1, 0, 2, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelSlice = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelSlice.setFont(font)
        self.labelSlice.setText("")
        self.labelSlice.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSlice.setObjectName("labelSlice")
        self.verticalLayout_2.addWidget(self.labelSlice)
        self.verticalSliderSlice = QtGui.QSlider(self.centralwidget)
        self.verticalSliderSlice.setAutoFillBackground(False)
        self.verticalSliderSlice.setMinimum(1)
        self.verticalSliderSlice.setMaximum(1)
        self.verticalSliderSlice.setSingleStep(0)
        self.verticalSliderSlice.setProperty("value", 1)
        self.verticalSliderSlice.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderSlice.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSliderSlice.setTickInterval(10)
        self.verticalSliderSlice.setObjectName("verticalSliderSlice")
        self.verticalLayout_2.addWidget(self.verticalSliderSlice)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 1, 1, 1)
        self.outputSpaxelWidget = MatplotlibImgWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputSpaxelWidget.sizePolicy().hasHeightForWidth())
        self.outputSpaxelWidget.setSizePolicy(sizePolicy)
        self.outputSpaxelWidget.setObjectName("outputSpaxelWidget")
        self.gridLayout.addWidget(self.outputSpaxelWidget, 2, 2, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem25 = QtGui.QSpacerItem(118, 28, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem25)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_19 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_3.addWidget(self.label_19)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButtonModeView = QtGui.QRadioButton(self.centralwidget)
        self.radioButtonModeView.setEnabled(False)
        self.radioButtonModeView.setChecked(True)
        self.radioButtonModeView.setObjectName("radioButtonModeView")
        self.horizontalLayout_2.addWidget(self.radioButtonModeView)
        self.radioButtonModeZoom = QtGui.QRadioButton(self.centralwidget)
        self.radioButtonModeZoom.setEnabled(False)
        self.radioButtonModeZoom.setObjectName("radioButtonModeZoom")
        self.horizontalLayout_2.addWidget(self.radioButtonModeZoom)
        self.radioButtonModeSelect = QtGui.QRadioButton(self.centralwidget)
        self.radioButtonModeSelect.setEnabled(False)
        self.radioButtonModeSelect.setObjectName("radioButtonModeSelect")
        self.horizontalLayout_2.addWidget(self.radioButtonModeSelect)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem26)
        self.checkBoxModeBoth = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxModeBoth.setEnabled(False)
        self.checkBoxModeBoth.setObjectName("checkBoxModeBoth")
        self.horizontalLayout_2.addWidget(self.checkBoxModeBoth)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_3)
        spacerItem27 = QtGui.QSpacerItem(148, 38, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem27)
        self.verticalLayout_13.addLayout(self.horizontalLayout_27)
        self.bothSpectrumWidget = MatplotlibSpecWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bothSpectrumWidget.sizePolicy().hasHeightForWidth())
        self.bothSpectrumWidget.setSizePolicy(sizePolicy)
        self.bothSpectrumWidget.setObjectName("bothSpectrumWidget")
        self.verticalLayout_13.addWidget(self.bothSpectrumWidget)
        self.horizontalLayout_60.addLayout(self.verticalLayout_13)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_60)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuMain = QtGui.QMenuBar(MainWindow)
        self.menuMain.setEnabled(True)
        self.menuMain.setGeometry(QtCore.QRect(0, 0, 1238, 25))
        self.menuMain.setDefaultUp(False)
        self.menuMain.setObjectName("menuMain")
        self.menuFile = QtGui.QMenu(self.menuMain)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtGui.QMenu(self.menuMain)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtGui.QMenu(self.menuMain)
        self.menuHelp.setObjectName("menuHelp")
        self.menuStart = QtGui.QMenu(self.menuMain)
        self.menuStart.setEnabled(False)
        self.menuStart.setObjectName("menuStart")
        MainWindow.setMenuBar(self.menuMain)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSetColours = QtGui.QAction(MainWindow)
        self.actionSetColours.setObjectName("actionSetColours")
        self.actionLoad_Cube = QtGui.QAction(MainWindow)
        self.actionLoad_Cube.setEnabled(True)
        self.actionLoad_Cube.setObjectName("actionLoad_Cube")
        self.actionSave_Results = QtGui.QAction(MainWindow)
        self.actionSave_Results.setEnabled(False)
        self.actionSave_Results.setObjectName("actionSave_Results")
        self.actionLoad_Configuration = QtGui.QAction(MainWindow)
        self.actionLoad_Configuration.setObjectName("actionLoad_Configuration")
        self.actionSave_Configuration = QtGui.QAction(MainWindow)
        self.actionSave_Configuration.setObjectName("actionSave_Configuration")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAboutQt = QtGui.QAction(MainWindow)
        self.actionAboutQt.setWhatsThis("")
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSubtraction = QtGui.QAction(MainWindow)
        self.actionSubtraction.setObjectName("actionSubtraction")
        self.actionMonte_Carlo_run = QtGui.QAction(MainWindow)
        self.actionMonte_Carlo_run.setObjectName("actionMonte_Carlo_run")
        self.actionSetQSOcentre = QtGui.QAction(MainWindow)
        self.actionSetQSOcentre.setCheckable(False)
        self.actionSetQSOcentre.setEnabled(False)
        self.actionSetQSOcentre.setObjectName("actionSetQSOcentre")
        self.actionManual = QtGui.QAction(MainWindow)
        self.actionManual.setObjectName("actionManual")
        self.menuFile.addAction(self.actionLoad_Cube)
        self.menuFile.addAction(self.actionSave_Results)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Configuration)
        self.menuFile.addAction(self.actionSave_Configuration)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionSetQSOcentre)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionSetColours)
        self.menuHelp.addAction(self.actionManual)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAboutQt)
        self.menuStart.addAction(self.actionSubtraction)
        self.menuStart.addAction(self.actionMonte_Carlo_run)
        self.menuMain.addAction(self.menuFile.menuAction())
        self.menuMain.addAction(self.menuStart.menuAction())
        self.menuMain.addAction(self.menuSettings.menuAction())
        self.menuMain.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "QDeblend3D", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFileIn.setText(QtGui.QApplication.translate("MainWindow", "Current IFU Data Cube:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxSelectRegions.setTitle(QtGui.QApplication.translate("MainWindow", "1. Select Spatial Regions", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonRegionRegular.setText(QtGui.QApplication.translate("MainWindow", "Regular Masks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "QSO Box size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Host Box width", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonRegionManual.setText(QtGui.QApplication.translate("MainWindow", "Custom Masks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "QSO", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonQSOSaveMask.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonQSOChangeMask.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Host", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonEELRSaveMask.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonEELRChangeMask.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxDisplayMask.setText(QtGui.QApplication.translate("MainWindow", "Show &Mask", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxSpecRegions.setTitle(QtGui.QApplication.translate("MainWindow", "2. Select Spectral Regions", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxRegions.setItemText(0, QtGui.QApplication.translate("MainWindow", "1 Broad + 1 Cont", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxRegions.setItemText(1, QtGui.QApplication.translate("MainWindow", "2 Broad + 1 Cont", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxRegions.setItemText(2, QtGui.QApplication.translate("MainWindow", "1 Broad + 2 Cont", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxRegions.setItemText(3, QtGui.QApplication.translate("MainWindow", "2 Broad + 2 Cont", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "1. Broad", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSaveBroad1.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonChangeBroad1.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "2. Broad", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSaveBroad2.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonChangeBroad2.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "1. Cont", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSaveCont1.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonChangeCont1.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "2. Cont", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSaveCont2.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonChangeCont2.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxInterpCont.setText(QtGui.QApplication.translate("MainWindow", "Interpolate Continuum", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxShowRegion.setText(QtGui.QApplication.translate("MainWindow", "Show &Regions", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxMethod.setTitle(QtGui.QApplication.translate("MainWindow", "3. Method Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Correction Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCorrMode.setItemText(0, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCorrMode.setItemText(1, QtGui.QApplication.translate("MainWindow", "Constant SFB", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCorrMode.setItemText(2, QtGui.QApplication.translate("MainWindow", "Manual factor", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCorrMode.setItemText(3, QtGui.QApplication.translate("MainWindow", "Host SFB model", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditSFBFactor.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonEditHostModel.setText(QtGui.QApplication.translate("MainWindow", "Edit Host Model", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Iterations:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Region use:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxRegionMeasure.setItemText(0, QtGui.QApplication.translate("MainWindow", "median", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxRegionMeasure.setItemText(1, QtGui.QApplication.translate("MainWindow", "mean", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxRegionMeasure.setItemText(2, QtGui.QApplication.translate("MainWindow", "sum", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonRadius.setText(QtGui.QApplication.translate("MainWindow", "Radius", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditRadius.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonStartSubtract.setText(QtGui.QApplication.translate("MainWindow", "Start &Deblending", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSaveResults.setText(QtGui.QApplication.translate("MainWindow", "&Save Cubes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Max:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Min:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAutoImg.setText(QtGui.QApplication.translate("MainWindow", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Max:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Min:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAutoSpec.setText(QtGui.QApplication.translate("MainWindow", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Input datacube", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Deblended datacube:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonHost.setText(QtGui.QApplication.translate("MainWindow", "Host", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonQSO.setText(QtGui.QApplication.translate("MainWindow", "QSO", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Mouse Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonModeView.setText(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonModeZoom.setText(QtGui.QApplication.translate("MainWindow", "&Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonModeSelect.setText(QtGui.QApplication.translate("MainWindow", "Se&lect", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxModeBoth.setText(QtGui.QApplication.translate("MainWindow", "display both", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "S&ettings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuStart.setTitle(QtGui.QApplication.translate("MainWindow", "S&tart", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetColours.setText(QtGui.QApplication.translate("MainWindow", "&Color Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Cube.setText(QtGui.QApplication.translate("MainWindow", "&Load Cube", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Results.setText(QtGui.QApplication.translate("MainWindow", "&Save Cubes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Configuration.setText(QtGui.QApplication.translate("MainWindow", "L&oad Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Configuration.setToolTip(QtGui.QApplication.translate("MainWindow", "Load Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Configuration.setText(QtGui.QApplication.translate("MainWindow", "S&ave Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutQt.setText(QtGui.QApplication.translate("MainWindow", "&AboutQt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutQt.setToolTip(QtGui.QApplication.translate("MainWindow", "AboutQt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "&Version", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSubtraction.setText(QtGui.QApplication.translate("MainWindow", "&Deblending", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMonte_Carlo_run.setText(QtGui.QApplication.translate("MainWindow", "&Monte Carlo run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMonte_Carlo_run.setToolTip(QtGui.QApplication.translate("MainWindow", "Monte Carlo run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetQSOcentre.setText(QtGui.QApplication.translate("MainWindow", "Set &QSO centre", None, QtGui.QApplication.UnicodeUTF8))
        self.actionManual.setText(QtGui.QApplication.translate("MainWindow", "Online Manual", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibspecwidget import MatplotlibSpecWidget
from matplotlibimgwidget import MatplotlibImgWidget
